services:
  meshcentral:
    image: ghcr.io/ylianst/meshcentral:1.1.57
    container_name: meshcentral
    restart: unless-stopped
    ports:
      - "8086:443"
    environment:
      - HOSTNAME=100.114.165.59
      - REVERSE_PROXY=false
      - ALLOW_NEW_ACCOUNTS=true
      - WEBRTC=false
      - NODE_ENV=production
      - USE_MONGODB=false
    volumes:
      - meshcentral-data:/opt/meshcentral/meshcentral-data
      - meshcentral-files:/opt/meshcentral/meshcentral-files
      - meshcentral-backups:/opt/meshcentral/meshcentral-backups
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  meshcentral-data:
  meshcentral-files:
  meshcentral-backups:
