services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - uptime-kuma/data:/app/data
    ports:
      - "3001:3001"
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  uptime-kuma-data:
